server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: INE4
  datasource:
    url: jdbc:mariadb://192.168.3.185:13307/ycbm
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ycbmclone@gmail.com
    password: vxovoyyurxgxlhsb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 885206176344-7ppl89dobit51bthb75u5tg5s9491o4k.apps.googleusercontent.com
            scope: email, profile, https://www.googleapis.com/auth/calendar, https://www.googleapis.com/auth/calendar.events
# logging:
#   level:
#     org.springframework.security: DEBUG
#   file:
#     name: application.log