server:
  post: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: INE4
  datasource:
    url: jdbc:mariadb://localhost:3307/ycbm
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
